### PR TITLE
Add clarification about Brigardier dependency

### PR DESCRIPTION
**Pull request by DRSchlaubi**

### CODE REVIEW

**Comment by bluefireoly** [comment]
Thanks, I would suggest  to also note there that the official Brigardier dependency does not include the Minecraft specific argument types, which you will often need.

**Comment by bluefireoly** [comment]
Brigardier itself does only include argument types for primitives and String: https://github.com/Mojang/brigadier/tree/master/src/main/java/com/mojang/brigadier/arguments

**Comment by DRSchlaubi** [comment]
Those will only be in the spigot API dependency?

**Comment by bluefireoly** [comment]
No they will only be in the `spigot` dependency generated by the BuildTools.

**Comment by DRSchlaubi** [comment]
> The minecraft argument types will only be in the `spigot` dependency generated by the BuildTools.
> The default argument types are always there, if you have any kind of Brigardier dependency added to your project.

Wouldn't it be smarter to support https://github.com/lucko/commodore instead as it supports the mc arguments and is also based on brigardier?

**Comment by bluefireoly** [comment]
I won't because:
- it isn't on Maven Central
- I really don't like it to add extra dependencies to KSpigot

We can add our own MC argument types to KSpigot itself in the future.

**Comment by bluefireoly** [comment]
> as it supports the mc arguments

where does it have argument types for blocks, locations, identifiers etc?

**Comment by DRSchlaubi** [comment]
> > as it supports the mc arguments
> 
> where does it have argument types for blocks, locations, identifiers etc?

I just assumed they would but it doesn't seem like they actually do

**Pull request merged**
